Repository opensearch-project/dashboards-maps, pull requests merged in 2022-11, with the labels that each got.

#82 Adds release notes for 2.4.0
  release-notes/opensearch-dashboards-maps.release-notes-2.4.0.0.md
Labels: v2.4.0

#87 Version bump to 2.4 for dependent packages
  .github/workflows/cypress-workflow.yml
  release-notes/opensearch-dashboards-maps.release-notes-2.4.0.0.md
  src/plugins/custom_import_map/opensearch_dashboards.json
Labels: backport 2.4

#88 Correct OSD import path for custom-import-map
  .github/workflows/unit-tests-workflow-for-customImportMap.yml
  custom_import_map/.babelrc
  custom_import_map/.eslintrc
  custom_import_map/.gitignore
  custom_import_map/.lintstagedrc
  custom_import_map/.prettierignore
  custom_import_map/.prettierrc
  custom_import_map/babel.config.js
  custom_import_map/common/constants/shared.ts
  custom_import_map/common/index.ts
  custom_import_map/common/util.ts
  custom_import_map/opensearch_dashboards.json
  custom_import_map/package.json
  custom_import_map/public/components/__snapshots__/show_error_modal.test.tsx.snap
  custom_import_map/public/components/__snapshots__/vector_upload_options.test.tsx.snap
  custom_import_map/public/components/show_error_modal.test.tsx
  custom_import_map/public/components/show_error_modal.tsx
  custom_import_map/public/components/vector_upload_options.scss
  custom_import_map/public/components/vector_upload_options.test.tsx
  custom_import_map/public/components/vector_upload_options.tsx
  custom_import_map/public/index.ts
  custom_import_map/public/plugin.tsx
  custom_import_map/public/services.ts
  custom_import_map/public/types.ts
  custom_import_map/server/clusters/geospatial_cluster.js
  custom_import_map/server/clusters/geospatial_plugin.ts
  custom_import_map/server/clusters/index.ts
  custom_import_map/server/index.ts
  custom_import_map/server/plugin.ts
  custom_import_map/server/routes/geospatial.ts
  custom_import_map/server/routes/index.ts
  custom_import_map/server/routes/opensearch.ts
  custom_import_map/server/services/geospatial_service.js
  custom_import_map/server/services/index.js
  custom_import_map/server/services/opensearch_service.js
  custom_import_map/server/services/utils/constants.ts
  custom_import_map/server/types.ts
  custom_import_map/test/enzyme.js
  custom_import_map/test/jest.config.js
  custom_import_map/test/mocks/styleMock.js
  custom_import_map/test/polyfills.js
  custom_import_map/test/polyfills/mutationObserver.js
  custom_import_map/test/setup.jest.js
  custom_import_map/test/setupTests.js
  custom_import_map/tsconfig.json
Labels: backport 2.x, Infrastructure

#80 Integrate layerList to store and add breadcrumbs
  maps_dashboards/common/index.ts
  maps_dashboards/public/components/app.tsx
  maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
  maps_dashboards/public/components/map_container/map_container.tsx
  maps_dashboards/public/components/map_page/map_page.tsx
  maps_dashboards/public/components/map_top_nav/get_top_nav_config.tsx
  maps_dashboards/public/components/map_top_nav/top_nav_menu.tsx
  maps_dashboards/public/components/maps_list/maps_list.tsx
  maps_dashboards/public/model/OSMLayerFunctions.ts
  maps_dashboards/public/model/layersFunctions.ts
  maps_dashboards/public/plugin.ts
  maps_dashboards/public/types.ts
  maps_dashboards/public/utils/breadcrumbs.ts
Labels: maps-dashboards
