Repository opensearch-project/dashboards-maps, pull requests merged in 2022-08, with the labels that each got.

#20 adds changes for releasing plugin with OSD as part of 2.2 release
  .github/workflows/unit-tests-workflow-for-customImportMap.yml
  DEVELOPER_GUIDE.md
  src/plugins/custom_import_map/package.json
  src/plugins/custom_import_map/public/components/vector_upload_options.test.tsx
  src/plugins/custom_import_map/public/components/vector_upload_options.tsx
  src/plugins/custom_import_map/public/plugin.tsx
  src/plugins/custom_import_map/public/services.ts
  src/plugins/custom_import_map/public/types.ts
  src/plugins/custom_import_map/server/index.ts
  src/plugins/custom_import_map/server/plugin.ts
  src/plugins/custom_import_map/test/jest.config.js
Labels: 2.2.0

#21 Add 2.2.0.0 release note
  release-notes/opensearch-dashboards-maps.release-notes-2.2.0.0.md
Labels: 2.2.0, release

#23 Update 2.2.0.0 release note
  release-notes/opensearch-dashboards-maps.release-notes-2.2.0.0.md
Labels: 2.2.0, release, backport 2.x

#27 Adds dashboards as suffix to plugin name
  src/plugins/custom_import_map/opensearch_dashboards.json
  src/plugins/custom_import_map/package.json
  src/plugins/custom_import_map/test/jest.config.js
Labels: 2.2.0, backport 2.2

#34 Add OpenSearch Dashboards context to component and common folder changes
  release-notes/opensearch-dashboards-maps.release-notes-2.2.0.0.md
  src/plugins/custom_import_map/.opensearch_dashboards-plugin-helpers.json
  src/plugins/custom_import_map/public/plugin.tsx
  src/plugins/custom_import_map/tsconfig.json
Labels: 2.2.0
