Repository opensearch-project/dashboards-maps, pull requests merged in 2023-01, with the labels that each got.

#123 [2.x]Migrate custom-import-map plugin to root and add build script
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow-for-customImportMap.yml
  custom_import_map/.babelrc
  custom_import_map/.eslintrc
  custom_import_map/.gitignore
  custom_import_map/.lintstagedrc
  custom_import_map/.opensearch_dashboards-plugin-helpers.json
  custom_import_map/.prettierignore
  custom_import_map/.prettierrc
  custom_import_map/babel.config.js
  custom_import_map/build.sh
  custom_import_map/common/constants/shared.ts
  custom_import_map/common/index.ts
  custom_import_map/common/util.ts
  custom_import_map/cypress.json
  custom_import_map/cypress/fixtures/sample_geojson.json
  custom_import_map/cypress/integration/geojson_file_upload.spec.js
  custom_import_map/cypress/integration/import_vector_map_tab.spec.js
  custom_import_map/cypress/plugins/index.js
  custom_import_map/cypress/support/commands.js
  custom_import_map/cypress/support/constants.js
  custom_import_map/cypress/support/index.js
  custom_import_map/cypress/utils/constants.js
  custom_import_map/opensearch_dashboards.json
  custom_import_map/package.json
  custom_import_map/public/components/__snapshots__/show_error_modal.test.tsx.snap
  custom_import_map/public/components/__snapshots__/vector_upload_options.test.tsx.snap
  custom_import_map/public/components/show_error_modal.test.tsx
  custom_import_map/public/components/show_error_modal.tsx
  custom_import_map/public/components/vector_upload_options.scss
  custom_import_map/public/components/vector_upload_options.test.tsx
  custom_import_map/public/components/vector_upload_options.tsx
  custom_import_map/public/index.ts
  custom_import_map/public/plugin.tsx
  custom_import_map/public/services.ts
  custom_import_map/public/types.ts
  custom_import_map/server/clusters/geospatial_cluster.js
  custom_import_map/server/clusters/geospatial_plugin.ts
  custom_import_map/server/clusters/index.ts
  custom_import_map/server/index.ts
  custom_import_map/server/plugin.ts
  custom_import_map/server/routes/geospatial.ts
  custom_import_map/server/routes/index.ts
  custom_import_map/server/routes/opensearch.ts
  custom_import_map/server/services/geospatial_service.js
  custom_import_map/server/services/index.js
  custom_import_map/server/services/opensearch_service.js
  custom_import_map/server/services/utils/constants.ts
  custom_import_map/server/types.ts
  custom_import_map/test/enzyme.js
  custom_import_map/test/jest.config.js
  custom_import_map/test/mocks/styleMock.js
  custom_import_map/test/polyfills.js
  custom_import_map/test/polyfills/mutationObserver.js
  custom_import_map/test/setup.jest.js
  custom_import_map/test/setupTests.js
  custom_import_map/tsconfig.json
Labels: Infrastructure

#182 Add fullWidth for large size screen display
  public/components/layer_config/custom_map_config/custom_map_source.tsx
  public/components/layer_config/documents_config/document_layer_source.tsx
  public/components/layer_config/documents_config/document_layer_style.tsx
  public/components/layer_config/layer_basic_settings.tsx
  yarn.lock
Labels: backport 2.x, backport 2.5

#185 Update helper text
  public/components/layer_config/custom_map_config/custom_map_source.tsx
Labels: v2.5.0, backport 2.x, backport 2.5

#188 Update layer type UI on config panel
  public/components/layer_config/layer_basic_settings.tsx
  public/components/layer_config/layer_config_panel.tsx
Labels: backport 2.x, backport 2.5

#196 Move maps entrypoint under plugins
  public/plugin.tsx
Labels: backport 2.x, backport 2.5

#199 Add release notes for 2.5
  release-notes/opensearch-dashboards-maps.release-notes-2.5.0.0.md
Labels: documentation, v2.5.0, backport 2.x, backport 2.5

#202 Support overriding maps config from OSD config yml file
  common/index.ts
  public/application.tsx
  public/components/add_layer_panel/add_layer_panel.tsx
  public/components/app.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/map_container.tsx
  public/components/map_page/map_page.tsx
  public/config.ts
  public/index.ts
  public/plugin.tsx
  public/utils/getIntialConfig.ts
  release-notes/opensearch-dashboards-maps.release-notes-2.5.0.0.md
  server/index.ts
Labels: enhancement, backport 2.x, backport 2.5

#205 fix config.ts not found issue
  common/config.ts
  public/application.tsx
  public/components/add_layer_panel/add_layer_panel.tsx
  public/components/app.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/map_container.tsx
  public/components/map_page/map_page.tsx
  public/index.ts
  public/plugin.tsx
  public/utils/getIntialConfig.ts
  server/index.ts
Labels: bug, v2.5.0, backport 2.x, Infrastructure, backport 2.5

#208 [2.5] Add OpenSearch Dashboards context to component and common folder …
  .opensearch_dashboards-plugin-helpers.json
  public/plugin.tsx
  tsconfig.json
Labels: bug, v2.5.0

#209 Add OpenSearch Dashboards context to component and common folder changes
  .opensearch_dashboards-plugin-helpers.json
  public/plugin.tsx
  tsconfig.json
Labels: bug, backport 2.x

#216 Limit max number of layers
  common/index.ts
  public/components/add_layer_panel/add_layer_panel.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
Labels: enhancement, v2.6.0

#218 [Cypress fix] Wait map saved before open maps listing
  .github/workflows/cypress-workflow.yml
  cypress/integration/documentsLayer.spec.js
Labels: backport 2.x, Infrastructure

#222 Refactor add layer operations
  public/model/documentLayerFunctions.ts
  public/model/map/__mocks__/layer.ts
  public/model/map/__mocks__/map.ts
  public/model/map/layer_operations.test.ts
  public/model/map/layer_operations.ts
Labels: backport 2.x, v2.6.0
