Repository opensearch-project/dashboards-maps, pull requests merged in 2023-09, with the labels that each got.

#462 Bump cypress version to ^13.1.0
  CHANGELOG.md
  cypress.config.js
  cypress.json
  cypress/e2e/add_map_to_dashboard.cy.js
  cypress/e2e/add_saved_object.cy.js
  cypress/e2e/documentsLayer.cy.js
  cypress/e2e/geojson_file_upload.cy.js
  cypress/e2e/import_vector_map_tab.cy.js
  cypress/e2e/opensearchMapLayer.cy.js
  cypress/support/e2e.js
  package.json
  public/components/toolbar/spatial_filter/__snapshots__/filter-by_shape.test.tsx.snap
  yarn.lock
Labels: backport 2.x, maintenance, 2.10.0, backport 2.10

#467 Update snap to pass unit test
  public/components/toolbar/spatial_filter/__snapshots__/filter-by_shape.test.tsx.snap
Labels: skip-changelog, 2.10.0

#464 Created release notes for 2.10 release
  CHANGELOG.md
  release-notes/opensearch-dashboards-maps.release-notes-2.10.0.0.md
Labels: backport 2.x, skip-changelog, v2.10.0, backport 2.10
