Repository opensearch-project/dashboards-maps, pull requests merged in 2023-02, with the labels that each got.

#224 Refactor layer operations
  public/components/layer_control_panel/layer_control_panel.tsx
  public/model/OSMLayerFunctions.ts
  public/model/customLayerFunctions.ts
  public/model/documentLayerFunctions.ts
  public/model/layersFunctions.ts
  public/model/map/__mocks__/map.ts
  public/model/map/layer_operations.test.ts
  public/model/map/layer_operations.ts
Labels: backport 2.x, v2.6.0

#225 Refactor layer properties as own interface
  public/model/customLayerFunctions.ts
  public/model/map/layer_operations.ts
Labels: backport 2.x, v2.6.0

#226 Fix popup display while zoomed out
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/map_container.tsx
  public/components/tooltip/create_tooltip.tsx
Labels: backport 2.x, v2.6.0

#232 Update 2.x branch version to 2.6
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  cypress/integration/documentsLayer.spec.js
  opensearch_dashboards.json
  package.json
Labels: maintenance

#235 Delete Sample data after running cypress test
  cypress/integration/documentsLayer.spec.js
  cypress/integration/opensearchMapLayer.spec.js
Labels: backport 2.x, Infrastructure

#239 Update development and maintainer document
  DEVELOPER_GUIDE.md
  MAINTAINERS.md
Labels: documentation, backport 2.x

#242 Refactor delete layer modal
  package.json
  public/components/layer_control_panel/delete_layer_modal.test.tsx
  public/components/layer_control_panel/delete_layer_modal.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
Labels: backport 2.x, v2.6.0, refactoring

#240 Add maps saved object for sample datasets
  cypress/integration/add_saved_object.spec.js
  opensearch_dashboards.json
  server/plugin.ts
  server/services/sample_data/flights_saved_objects.ts
  server/types.ts
Labels: enhancement, backport 2.x, v2.6.0

#263 Add close button to tooltip hover
  public/components/map_container/map_container.tsx
  public/components/tooltip/create_tooltip.tsx
Labels: bug, backport 2.x

#256 Align items in add new layer modal
  public/components/add_layer_panel/add_layer_panel.scss
  public/components/add_layer_panel/add_layer_panel.tsx
Labels: enhancement

#271 Refactor layer handler into parent component
  public/components/layer_config/documents_config/document_layer_config_panel.tsx
  public/components/layer_config/layer_config_panel.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/map_container.tsx
  public/components/map_page/map_page.tsx
  public/components/map_top_nav/top_nav_menu.tsx
  public/embeddable/map_component.tsx
  public/model/layerRenderController.ts
  public/model/layersFunctions.ts
Labels: backport 2.x, v2.6.0, refactoring

#272 Add indexPatterns to map embeddable output for dashboard filters
  public/embeddable/map_embeddable.tsx
  public/embeddable/map_embeddable_factory.tsx
Labels: enhancement, backport 2.x, v2.6.0

#252 Refactor hide layer button
  public/components/layer_control_panel/hide_layer_button.test.tsx
  public/components/layer_control_panel/hide_layer_button.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/model/documentLayerFunctions.ts
  public/model/map/layer_operations.test.ts
  public/model/map/layer_operations.ts
Labels: backport 2.x, v2.6.0, refactoring, backport 2.6

#277 Fix Node.js and Yarn installation in CI
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x, v2.6.0, Infrastructure, backport 2.6

#276 Fix property value's non null check
  public/model/documentLayerFunctions.ts
Labels: bug, backport 2.x, v2.6.0, backport 2.6

#282 [Backport 2.x][Manual]Fix Node.js and Yarn installation in CI (#277)
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.6

#286 Add 2.6.0 release notes
  release-notes/opensearch-dashboards-maps.release-notes-2.6.0.0.md
Labels: documentation, backport 2.x, v2.6.0, backport 2.6

#289 Fix custom layer render opacity config
  public/model/customLayerFunctions.ts
  release-notes/opensearch-dashboards-maps.release-notes-2.6.0.0.md
Labels: bug, backport 2.x, v2.6.0, backport 2.6

#294 Show scroll bar when panel height reaches container bottom
  .gitignore
  public/components/layer_control_panel/layer_control_panel.scss
Labels: enhancement, v2.7.0

#299 Enhance layer visibility status display
  public/components/layer_control_panel/layer_control_panel.tsx
Labels: enhancement, backport 2.x, v2.7.0

#297 Add custom layer visibility config to render
  public/model/customLayerFunctions.ts
Labels: bug, backport 2.x, v2.7.0
