Repository opensearch-project/dashboards-maps, pull requests merged in 2023-04, with the labels that each got.

#372 Update draw filter shape ui properties
  CHANGELOG.md
  common/index.ts
  public/components/map_container/map_container.scss
  public/components/map_container/map_container.tsx
  public/components/toolbar/spatial_filter/__snapshots__/filter-by_shape.test.tsx.snap
  public/components/toolbar/spatial_filter/__snapshots__/filter_by_polygon.test.tsx.snap
  public/components/toolbar/spatial_filter/__snapshots__/filter_by_rectangle.test.tsx.snap
  public/components/toolbar/spatial_filter/__snapshots__/filter_toolbar.test.tsx.snap
  public/components/toolbar/spatial_filter/display_draw_helper.test.tsx
  public/components/toolbar/spatial_filter/display_draw_helper.tsx
  public/components/toolbar/spatial_filter/draw_filter_shape.tsx
  public/components/toolbar/spatial_filter/draw_style.ts
  public/components/toolbar/spatial_filter/draw_tooltip.tsx
  public/components/toolbar/spatial_filter/filter-by_shape.test.tsx
  public/components/toolbar/spatial_filter/filter_by_polygon.test.tsx
  public/components/toolbar/spatial_filter/filter_by_rectangle.test.tsx
  public/components/toolbar/spatial_filter/filter_by_rectangle.tsx
  public/components/toolbar/spatial_filter/filter_by_shape.tsx
  public/components/toolbar/spatial_filter/filter_toolbar.tsx
  public/images/polygon.svg
Labels: backport 2.x, v2.7.0, backport 2.7

#371 Add filter bar to display global geospatial filters
  CHANGELOG.md
  public/components/filter_bar/__snapshots__/filter_bar.test.tsx.snap
  public/components/filter_bar/__snapshots__/filter_editor.test.tsx.snap
  public/components/filter_bar/__snapshots__/filter_view.test.tsx.snap
  public/components/filter_bar/filter_actions.test.ts
  public/components/filter_bar/filter_actions.ts
  public/components/filter_bar/filter_bar.test.tsx
  public/components/filter_bar/filter_bar.tsx
  public/components/filter_bar/filter_editor.test.tsx
  public/components/filter_bar/filter_editor.tsx
  public/components/filter_bar/filter_item.tsx
  public/components/filter_bar/filter_options.tsx
  public/components/filter_bar/filter_view.test.tsx
  public/components/filter_bar/filter_view.tsx
  public/components/map_container/map_container.tsx
  public/components/map_page/map_page.tsx
  public/components/toolbar/spatial_filter/draw_filter_shape.tsx
  public/components/toolbar/spatial_filter/spatial_filter.scss
  public/model/layerRenderController.ts
Labels: backport 2.x, v2.7.0, backport 2.7

#362 Add stats API for maps and layers in maps plugin
  CHANGELOG.md
  common/index.ts
  public/model/mapLayerType.ts
  server/common/stats/stats_helper.test.ts
  server/common/stats/stats_helper.ts
  server/plugin.ts
  server/routes/index.ts
  server/routes/stats_router.ts
Labels: backport 2.x, Infrastructure, v2.7.0, backport 2.7

#370 Add search query ability on map
  CHANGELOG.md
  public/components/map_container/map_container.tsx
  public/components/map_page/map_page.tsx
  public/components/map_top_nav/top_nav_menu.tsx
  public/embeddable/map_component.tsx
  public/model/layerRenderController.ts
Labels: feature, backport 2.x, v2.7.0, backport 2.7

#387 Add before layer id when adding documents label
  CHANGELOG.md
  common/map_saved_object_attributes.ts
  public/components/layer_config/layer_config_panel.tsx
  public/components/layer_control_panel/hide_layer_button.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/map_container.tsx
  public/model/OSMLayerFunctions.ts
  public/model/customLayerFunctions.ts
  public/model/documentLayerFunctions.ts
  public/model/layerRenderController.ts
  public/model/layersFunction.test.ts
  public/model/layersFunctions.ts
  public/model/map/layer_operations.test.ts
  public/model/map/layer_operations.ts
Labels: enhancement, backport 2.x, v2.7.0, backport 2.7

#382 Toast Warning Message if OpenSearch base map is used in conflicting regions
  CHANGELOG.md
  public/components/map_container/map_container.tsx
  public/components/map_container/maps_messages.tsx
  public/model/OSMLayerFunctions.ts
  public/model/layerRenderController.ts
Labels: enhancement, backport 2.x, v2.7.0, backport 2.7

#392 Add 2.7.0 Release Notes
  CHANGELOG.md
  release-notes/opensearch-dashboards-maps.release-notes-2.7.0.0.md
Labels: backport 2.x, v2.7.0, skip-changelog, backport 2.7

#400 Remove package-lock.json
  CHANGELOG.md
  package-lock.json
Labels: backport 2.x, v2.8.0, maintenance

#401 Fix failing cypress test
  cypress/integration/add_saved_object.spec.js
Labels: backport 2.x, skip-changelog
