Repository opensearch-project/dashboards-maps, pull requests merged in 2023-03, with the labels that each got.

#234 fix: filters not reset when index pattern changed
  public/components/layer_config/documents_config/document_layer_source.tsx
Labels: bug, v3.0.0, backport 2.x, v2.7.0

#305 Fix color picker component issue
  common/index.ts
  public/components/layer_config/documents_config/document_layer_style.tsx
  public/utils/getIntialConfig.ts
Labels: bug, backport 2.x, v2.7.0

#309 Move zoom and coordinates as separate component
  public/components/map_container/map_container.tsx
  public/components/map_container/mapsFooter.test.tsx
  public/components/map_container/mapsFooter.tsx
Labels: backport 2.x, v2.7.0, refactoring

#313 Introduce disable tooltip on hover property
  common/index.ts
  public/components/map_container/map_container.tsx
  public/components/tooltip/create_tooltip.tsx
  public/model/mapLayerType.ts
  public/utils/getIntialConfig.ts
Labels: enhancement, backport 2.x, v2.7.0

#315 Move coordinates to footer
  public/components/map_container/map_container.tsx
  public/components/map_container/mapsFooter.test.tsx
  public/components/map_container/maps_footer.test.tsx
  public/components/map_container/maps_footer.tsx
Labels: backport 2.x, v2.7.0, refactoring

#317 Update tooltip behavior change
  common/index.ts
  public/components/layer_config/documents_config/document_layer_source.tsx
  public/components/tooltip/create_tooltip.tsx
  public/model/mapLayerType.ts
  public/utils/getIntialConfig.ts
Labels: enhancement, backport 2.x

#332 Update max supported layer count
  common/index.ts
Labels: enhancement, backport 2.x

#328 Refactor get field options and add field label option on UI
  common/index.ts
  public/components/layer_config/documents_config/document_layer_config_panel.tsx
  public/components/layer_config/documents_config/document_layer_source.tsx
  public/components/layer_config/documents_config/style/document_layer_style.tsx
  public/components/layer_config/documents_config/style/label_config.scss
  public/components/layer_config/documents_config/style/label_config.test.tsx
  public/components/layer_config/documents_config/style/label_config.tsx
  public/model/map/layer_operations.ts
  public/model/mapLayerType.ts
  public/utils/fields_options.test.ts
  public/utils/fields_options.ts
  public/utils/getIntialConfig.ts
Labels: backport 2.x, v2.7.0, refactoring

#247 Add rectangle as custom mode
  package.json
  public/components/draw/modes/rectangle.ts
  yarn.lock
Labels: enhancement, v2.7.0

#330 Add tooltip to draw shape filter
  public/components/map_container/map_container.tsx
  public/components/toolbar/spatial_filter/draw_tooltip.tsx
  public/components/toolbar/spatial_filter/filter_input_panel.tsx
Labels: backport 2.x

#336 Support adding field label to document layer
  common/index.ts
  public/components/layer_config/documents_config/document_layer_source.tsx
  public/components/layer_config/documents_config/style/document_layer_style.tsx
  public/components/layer_config/documents_config/style/label_config.scss
  public/components/layer_config/documents_config/style/label_config.test.tsx
  public/components/layer_config/documents_config/style/label_config.tsx
  public/model/documentLayerFunctions.ts
  public/model/layerRenderController.ts
  public/model/map/__mocks__/layer.ts
  public/model/map/layer_operations.test.ts
  public/model/map/layer_operations.ts
  public/model/mapLayerType.ts
  public/utils/getIntialConfig.ts
Labels: feature, backport 2.x, v2.7.0

#342 Add CHANGELOG
  .github/workflows/changelog_verifier.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: backport 2.x

#340 BWC for label textType
  CHANGELOG.md
  public/components/layer_config/documents_config/style/label_config.tsx
  public/model/documentLayerFunctions.ts
  public/model/map/layer_operations.ts
Labels: enhancement, backport 2.x, v2.7.0

#339 Fix data query in dashboard mode when enable around map filter
  CHANGELOG.md
  public/components/map_container/map_container.tsx
  public/model/layerRenderController.ts
  public/model/layersFunctions.ts
  public/model/mapLayerType.ts
Labels: bug, backport 2.x, v2.7.0, backport 2.6

#347 Add mapbox-gl draw mode
  CHANGELOG.md
  common/index.ts
  public/components/map_container/map_container.tsx
  public/components/toolbar/spatial_filter/draw_filter_shape.tsx
  public/components/toolbar/spatial_filter/filter_by_polygon.tsx
Labels: backport 2.x, v2.7.0

#312 feat: add localization for opensearch base map
  common/index.ts
  common/util.ts
  public/model/OSMLayerFunctions.ts
Labels: feature, backport 2.x, v2.7.0

#350 Avoid trigger tooltip from label
  CHANGELOG.md
  public/components/tooltip/display_features.tsx
Labels: enhancement, backport 2.x, v2.7.0

#353 Sync maplibre layer order after layers rendered
  CHANGELOG.md
  public/components/map_container/map_container.tsx
  public/components/map_top_nav/top_nav_menu.tsx
  public/model/OSMLayerFunctions.ts
  public/model/customLayerFunctions.ts
  public/model/documentLayerFunctions.ts
  public/model/layerRenderController.ts
  public/model/layersFunctions.ts
  public/model/map/layer_operations.ts
Labels: bug, good first issue, backport 2.x, v2.7.0

#356 [2.x] Bump to 2.7.0 version
  CHANGELOG.md
  opensearch_dashboards.json
  package.json
Labels: v2.7.0, maintenance

#359 Remove cancel button on draw shape and use Escape to cancel draw
  CHANGELOG.md
  common/util.ts
  public/components/draw/modes/rectangle.ts
  public/components/map_container/map_container.tsx
  public/components/toolbar/spatial_filter/__snapshots__/filter_toolbar.test.tsx.snap
  public/components/toolbar/spatial_filter/draw_tooltip.tsx
  public/components/toolbar/spatial_filter/filter_toolbar.tsx
Labels: backport 2.x, v2.7.0

#364 Update listener on KeyUp
  CHANGELOG.md
  public/components/draw/modes/rectangle.ts
  public/components/toolbar/spatial_filter/draw_tooltip.tsx
Labels: backport 2.x, v2.7.0

#365 Add global geo shape filter while rendering data layers
  CHANGELOG.md
  common/index.ts
  public/components/layer_config/documents_config/document_layer_source.tsx
  public/components/map_container/map_container.tsx
  public/model/layerRenderController.ts
  public/model/mapLayerType.ts
  public/model/mapState.ts
  public/utils/getIntialConfig.ts
Labels: backport 2.x, v2.7.0
