Repository opensearch-project/dashboards-maps, pull requests merged in 2023-05, with the labels that each got.

#415 [backport 2.x][manually]Update repo owners and maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#409 Add Auto Release Workflow
  .github/workflows/auto-release.yml
Labels: backport 2.x, skip-changelog

#417 Adding release notes for 2.8
  CHANGELOG.md
  release-notes/opensearch-dashboards-maps.release-notes-2.8.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.8

#418 Clean console indexPatterns api error
  public/components/map_container/map_container.tsx
Labels: backport 2.x, skip-changelog, backport 2.8
