Repository opensearch-project/dashboards-maps, pull requests merged in 2024-08, with the labels that each got.

#647 Use smaller and compressed varients of buttons and form components
  public/components/__snapshots__/vector_upload_options.test.tsx.snap
  public/components/filter_bar/__snapshots__/filter_editor.test.tsx.snap
  public/components/filter_bar/filter_editor.tsx
  public/components/filter_bar/filter_options.tsx
  public/components/layer_config/custom_map_config/custom_map_source.tsx
  public/components/layer_config/documents_config/document_layer_source.tsx
  public/components/layer_config/documents_config/style/color_picker.tsx
  public/components/layer_config/documents_config/style/document_layer_style.tsx
  public/components/layer_config/documents_config/style/label_config.test.tsx
  public/components/layer_config/documents_config/style/label_config.tsx
  public/components/layer_config/layer_basic_settings.test.tsx
  public/components/layer_config/layer_basic_settings.tsx
  public/components/layer_config/layer_config_panel.tsx
  public/components/maps_list/maps_list.tsx
  public/components/show_error_modal.tsx
  public/components/tooltip/tooltipHeaderContent.tsx
  public/components/tooltip/tooltipTable.tsx
  public/components/vector_upload_options.tsx
Labels: backport 2.x, skip-changelog, v2.17

#651 Deprecate maps multi data source display
  CHANGELOG.md
  opensearch_dashboards.json
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/map_container.tsx
  public/components/map_page/map_page.tsx
  public/components/map_top_nav/top_nav_menu.tsx
  public/components/maps_list/maps_list.tsx
  public/plugin.tsx
  public/types.ts
Labels: backport 2.x, v2.17

#653 Use new header to maps listing page
  CHANGELOG.md
  public/components/maps_list/maps_list.tsx
Labels: feature, v2.17, feature branch

#654 Conditionally use the new Application Header variant on the Maps visualization page
  CHANGELOG.md
  public/components/map_top_nav/get_top_nav_config.tsx
  public/components/map_top_nav/top_nav_menu.tsx
Labels: feature, v2.17, feature branch

#655 Conditionally use full width for Maps listing page table
  CHANGELOG.md
  public/components/maps_list/maps_list.tsx
Labels: feature, v2.17, feature branch

#656 [feature to main] Use new header in Maps when new home UI is enabled
  CHANGELOG.md
  public/components/map_top_nav/get_top_nav_config.tsx
  public/components/map_top_nav/top_nav_menu.tsx
  public/components/maps_list/maps_list.tsx
Labels: feature, backport 2.x, v2.17

#659 [Look & Feel] Consistency and Density Changes
  CHANGELOG.md
  public/components/__snapshots__/vector_upload_options.test.tsx.snap
  public/components/add_layer_panel/add_layer_panel.tsx
  public/components/filter_bar/filter_item.tsx
  public/components/filter_bar/filter_options.tsx
  public/components/layer_config/base_map_layer_config_panel.tsx
  public/components/layer_config/custom_map_config/custom_map_config_panel.tsx
  public/components/layer_config/documents_config/document_layer_config_panel.tsx
  public/components/layer_config/layer_config_panel.tsx
  public/components/layer_control_panel/delete_layer_modal.test.tsx
  public/components/layer_control_panel/delete_layer_modal.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/maps_messages.tsx
  public/components/maps_list/maps_list.tsx
  public/components/show_error_modal.tsx
  public/components/toolbar/spatial_filter/display_draw_helper.tsx
  public/components/toolbar/spatial_filter/filter_by_shape.tsx
  public/components/toolbar/spatial_filter/filter_input_panel.tsx
  public/components/vector_upload_options.tsx
Labels: backport 2.x, v2.17

#664 Use functional test repo to run maps integration test workflow
  .github/workflows/cypress-workflow.yml
  .github/workflows/remote-ftr-integ-test-workflow.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  cypress.config.js
  cypress/e2e/add_map_to_dashboard.cy.js
  cypress/e2e/add_saved_object.cy.js
  cypress/e2e/documentsLayer.cy.js
  cypress/e2e/geojson_file_upload.cy.js
  cypress/e2e/import_vector_map_tab.cy.js
  cypress/e2e/opensearchMapLayer.cy.js
  cypress/fixtures/sample_geojson.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/constants.js
  cypress/support/e2e.js
  cypress/utils/constants.js
  package.json
  yarn.lock
Labels: Infrastructure
