Repository opensearch-project/dashboards-maps, pull requests merged in 2024-04, with the labels that each got.

#605 Fix zoom level type error in custom layer
  CHANGELOG.md
  public/components/layer_config/layer_basic_settings.test.tsx
  public/components/layer_config/layer_basic_settings.tsx
  public/model/customLayerFunctions.test.ts
  public/model/customLayerFunctions.ts
Labels: bug, v2.14.0

#611 Support multi data source display in Maps app
  CHANGELOG.md
  opensearch_dashboards.json
  public/application.tsx
  public/components/app.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_container/map_container.tsx
  public/components/map_page/map_page.tsx
  public/components/map_top_nav/top_nav_menu.tsx
  public/components/maps_list/maps_list.tsx
  public/plugin.tsx
  public/types.ts
  yarn.lock
Labels: feature, v2.14.0

#616 Add 2.14 release notes
  CHANGELOG.md
  release-notes/opensearch-dashboards-maps.release-notes-2.14.0.0.md
Labels: backport 2.x, skip-changelog
