Repository opensearch-project/dashboards-maps, pull requests merged in 2024-10, with the labels that each got.

#680 fix: prevent overlay from overlapping new application header
  CHANGELOG.md
  public/components/layer_config/layer_config_panel.tsx
Labels: bug, backport 2.x

#678 Fix dynamic uses of i18n
  CHANGELOG.md
  public/components/layer_config/documents_config/style/document_layer_style.tsx
  public/components/layer_config/documents_config/style/label_config.tsx
  public/components/layer_control_panel/layer_control_panel.tsx
  public/components/map_top_nav/get_top_nav_config.tsx
Labels: bug, backport 2.x

#683 Add multi data source dependencies plugins
  opensearch_dashboards.json
Labels: backport 2.x, skip-changelog

#684 [backport 2.x] Add multi data source dependencies plugins
  opensearch_dashboards.json
Labels: skip-changelog

#685 Add Release Notes for 2.18.0.0
  CHANGELOG.md
  release-notes/opensearch-dashboards-maps.release-notes-2.18.0.0.md
Labels: backport 2.x
