Repository opensearch-project/dashboards-maps, pull requests merged in 2024-07, with the labels that each got.

#631 Refresh custom wms layer+source on update (issue 601)
  CHANGELOG.md
  public/model/customLayerFunctions.test.ts
  public/model/customLayerFunctions.ts
Labels: bug, backport 2.x, v2.16.0, backport 2.15

#635 Add support new navigation for maps
  CHANGELOG.md
  public/plugin.tsx
Labels: feature, backport 2.x, v2.16.0

#637 Update new navigation groups
  public/plugin.tsx
Labels: backport 2.x, skip-changelog, v2.16.0

#639 Adds release notes for 2.16
  CHANGELOG.md
  release-notes/opensearch-dashboards-maps.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16

#643 [navigation]feat: do not show in all use case
  public/plugin.tsx
Labels: backport 2.x, skip-changelog, backport 2.16
