Repository opensearch-project/dashboards-maps, pull requests merged in 2024-09, with the labels that each got.

#666 Add release notes for 2.17
  CHANGELOG.md
  release-notes/opensearch-dashboards-maps.release-notes-2.17.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.17

#675 Bump up actions/upload-artifact to v4
  .github/workflows/remote-ftr-integ-test-workflow.yml
Labels: backport 2.x, skip-changelog

#674 [navigation]feat: update category to flatten menus in analytics(all) use case
  CHANGELOG.md
  public/plugin.tsx
Labels: backport 2.x
